name: Build and Tests

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build:
    defaults:
      run:
        working-directory: ./src
    runs-on: ubuntu-latest
    env: 
      VSTEST_CONNECTION_TIMEOUT: 900

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: | 
          6.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore 
    - name: Test
      run: dotnet test --no-restore --verbosity normal
