name: Release

on:
  release:
    types: [published]

jobs:
  
  release:
    runs-on: ubuntu-latest
    env:
      VERSION: 1.2.3
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build ./src/GeoJSON.Text.sln --configuration Release --no-restore /p:Version=$VERSION
      - name: Pack
        run: dotnet pack -c Release -p:PackageVersion=$VERSION